In [42]:
import numpy as np

In [43]:
ip=np.array([[0,0],[0,1],[1,1],[1,0]])
ip.shape
ip

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [44]:
op=np.array([0,1,1,1])
op=op.reshape(4,1)
op.shape

(4, 1)

In [45]:
w=np.array([[0.1],[0.2]])
w

array([[0.1],
       [0.2]])

In [46]:
bias=0.3

In [47]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [48]:
def der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [51]:
for i in range(10000):
    iparray=ip
    wsum=np.dot(iparray,w)+bias
    firstop=sigmoid(wsum)
    
    error=firstop-op
    toterror=np.square(np.subtract(firstop,op)).mean()
    
    firstder=error
    seconder=der(firstop)
    derivate=firstder*seconder
    
    tinput=ip.T
    finalder=np.dot(tinput,derivate)
    
    w=w-0.05*finalder
    for i in derivate:
        bias=bias-0.05*i
        
print(w)
print(bias)

[[7.00922425]
 [7.00953281]]
[-3.14905135]


In [52]:
predict=np.array([1,1])
result=np.dot(predict,w)+bias
res=sigmoid(result)
print(res)

[0.99998097]
